Repository NCAR/geocat-applications, pull requests merged in 2024-07, with the labels that each got.

#40 Trig functions and NCL receipt
  ncl/ncl_entries/ncl_entries.rst
  ncl/ncl_entries/trigonometric_functions.ipynb
  ncl/ncl_index/ncl-index-table.csv
  ncl/ncl_raw/trigonometric_functions.ncl
  ncl/receipts/trigonometric_functions.ipynb
Labels: documentation

#69 Inverse/Hyperbolic Trig Functions and NCL Receipt
  ncl/ncl_entries/trigonometric_functions.ipynb
  ncl/ncl_index/ncl-index-table.csv
  ncl/ncl_raw/trigonometric_functions.ncl
  ncl/receipts/trigonometric_functions.ipynb
Labels: ncl receipt, ncl entry

#83 add .codespellrc
  .codespellrc
Labels: testing, developer feature

#84 Reorganize `ncl_entries.ncl`
  index.rst
  ncl/ncl_entries/ncl_entries.rst
Labels: bug, developer feature
