Repository NCAR/geocat-applications, pull requests merged in 2024-08, with the labels that each got.

#77 General Applied Math Functions
  applications/applications.rst
  applications/data_analysis/data_analysis.rst
  applications/data_analysis/general_applied_math.ipynb
  ncl/ncl_entries/general_applied_math.ipynb
  ncl/ncl_entries/ncl_entries.rst
  ncl/ncl_index/ncl-index-table.csv
  ncl/ncl_raw/general_applied_math.ncl
  ncl/receipts/general_applied_math.ipynb
Labels: ncl, python entry, ncl receipt, ncl entry

#89 Adding Google Analytics
  conf.py
Labels: developer feature

#96 Getting Started Guide
  CONTRIBUTING.md
  GETTING_STARTED.md
  README.md
  index.rst
Labels: documentation, developer feature

#102 Execute notebooks at documentation generation
  .github/workflows/build.yml
  applications/data_analysis/climatology.ipynb
  applications/data_analysis/general_applied_math.ipynb
  applications/date_time/datetime.ipynb
  conf.py
  environment.yml
  ncl/ncl_entries/day_of_week.ipynb
  ncl/ncl_entries/days_in_month.ipynb
  ncl/ncl_entries/general_applied_math.ipynb
  ncl/ncl_entries/trigonometric_functions.ipynb
  ncl/receipts/days_in_month.ipynb
  ncl/receipts/general_applied_math.ipynb
  ncl/receipts/trigonometric_functions.ipynb
Labels: documentation, testing, developer feature, dependencies

#109 Add pooch/geocat-comp for geocat-datafiles
  environment.yml
Labels: developer feature
