Repository NCAR/geocat-applications, pull requests merged in 2024-05, with the labels that each got.

#20 Minimal PR and issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/general_issue.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, developer feature

#23 Add Pre-commit hooks
  .pre-commit-config.yaml
  CONTRIBUTING.md
  _static/custom.css
  applications/data_analysis/data_analysis.rst
  applications/data_analysis/sample.ipynb
  applications/file_io/file_io.rst
  applications/file_io/sample.ipynb
  applications/plot_types/contour.ipynb
  applications/plot_types/plot_types.rst
  conf.py
  environment.yml
  plot_types/template.ipynb
  references.bib
  ruff.toml
Labels: testing, developer feature

#28 File structure
  CONTRIBUTING.md
  Makefile
  README.md
  applications/applications.rst
  applications/ncl_applications.rst
  conf.py
  index.rst
  make.bat
  ncl/ncl_index.rst
  ncl/ncl_index/ncl-index-table.csv
  ncl/ncl_index/ncl_index.rst
  ncl/receipts/receipts.rst
  ncl/receipts/something-else.ipynb
  ncl/receipts/something.ipynb
  templates/NCL_template.ipynb
  templates/computational_template.ipynb
  templates/plot-template.ipynb
Labels: documentation, refactor

#30 Preview, deployment, comments, publish
  .github/workflows/build.yml
  .github/workflows/delete-preview.yml
  .github/workflows/deploy.yml
  .github/workflows/gh-pages.yml
  .github/workflows/preview-comment.yml
  .github/workflows/publish.yml
  .github/workflows/trigger-build.yml
  .github/workflows/trigger-preview.yml
Labels: documentation, testing, refactor, developer feature

#34 Add dependabot
  .github/dependabot.yml
Labels: testing, developer feature

#33 Add CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, developer feature
